name: Build PBR

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: download cidr
      run: |
        chmod +x ros-dpbr-CT-CMCC.sh
        ./ros-dpbr-CT-CMCC.sh

    - name: Commit
      run: |
        git config --global user.email dingkx19930215@gmail.com
        git config --global user.name JohnsonDKX
        git init
        git add .
        git commit -am "Auto PBR"

    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        force: true
