name: Build PBR

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: download cidr
      run: |
        chmod +x ros-dpbr-CT-CMCC.sh
        ./ros-dpbr-CT-CMCC.sh
        
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        force: true
